synonym_map = {
    'sweeetness': 'sweet', 'bitterness': 'bitter',
    'spiciness': 'spice', 'spicy': 'spice', 'alcoholic': 'alcohol', 'warmth': 'warm',
    'warms': 'warm', 'warming': 'warm', 'nuttiness': 'nut', 'nutty': 'nut',
    'roasted': 'roast', 'biscuity': 'biscuit', 'boozy': 'booze', 
    'bodied': 'body', 'bready': 'bread', 'toasty': 'toast', 'citrusy': 'citrus', 
    'earthiness': 'earthy', 'fruity': 'fruit', 'funky': 'funk', 'golden': 'gold', 
    'hazy': 'haze', 'grassy': 'grass', 'ipas':'ipa', 'rind': 'peel',
    'slight':'light', 'faint':'light', 'carbonated': 'carbonation',
    'little':'light', 'low':'light', 'moderate':'medium', 'heavy': 'strong',
    'full': 'strong', 'malty':'malt', 'boozy': 'alcohol', 'booze': 'alcohol',
    'watered': 'water', 'watery': 'water', 'hoppy': 'hop', 'fruitiness':'fruit',
    'tartness': 'tart', 'lightly': 'light', 'hint': 'light', 'reddish': 'red',
    'buttery': 'butter', 'piney': 'pine', 'mildy': 'mild', 'sourness': 'sour',
    'syrupy': 'syrup', 'peppery': 'pepper', 'cloudy': 'haze', 'haziness': 'haze',
    'cloudiness': 'haze', 'hazed': 'haze', 'transparent': 'clear', 'translucent': 'clear',
    'turbid': 'haze', 'stickiness': 'sticky', 'lacing': 'head', 'doughy': 'dough',
    'yellowish': 'light_yellow', 'pinkish': 'light_pink', 'milky': 'milk',
    'fluffy': 'frothy', 'pillowy': 'frothy', 'salinity': 'salt', 'saltiness': 'salt',
    'brine': 'salt', 'lighter': 'light', 'burn': 'warm', 'heat': 'warm',
    'straightforward': 'simple', 'basic': 'simple', 'roasty': 'roast', 'crackery': 'cracker',
    'maltiness': 'malt', 'sessonability': 'sessionable', 'lemony': 'lemon'
}

phrase_map = {
    'bit_water': 'water', 'thin_water': 'water', 'light_water': 'water',
    'coffee_light': 'light_coffee', 'beer_light': 'light_beer', 'smell_light': 'light_smell',
    'light_sweet': 'semi_sweet',
    'slightly_sweet': 'semi_sweet', 'slightly_bitter': 'semi_bitter', 'light_sweetness': 'semi_sweet',
    'sweetness_light': 'semi_sweet', 'aroma_light': 'light_aroma', 'head_light': 'light_head',
    'malt_light': 'light_malt', 'flavor_light': 'light_flavor', 'light_taste': 'light_flavor',
    'slightly_haze': 'light_haze', 'color_light': 'light_color',
    'body_medium': 'medium_body', 'slightly_cloudy': 'light_haze', 'light_gold': 'light_yellow',
    'slightly_fruit': 'light_fruit', 'slightly_hop': 'light_hoppy', 'dipa': 'double_ipa',
    'sessionable': 'session_beer', 'bitter_dark_chocolate': 'dark_chocolate',
    'opaque_black': 'pitch_black', 'jet_black': 'pitch_black', 'deep_black': 'pitch_black',
    'dark_brown_almost_black': 'near_black', 'almost_black': 'near_black', 'nearly_black': 'near_black',
    'dark_ruby': 'dark_red', 'dark_cherry': 'black_cherry', 'candied_sugar': 'candy_sugar',
    'candi_sugar': 'candy_sugar', 'sugary_sweetness': 'strong_sweet', 'easy_drink': 'easy_drinking',
    'pale_gold': 'light_yellow', 'pale_yellow': 'light_yellow', 'pale_straw': 'light_yellow',
    'alcohol_warm': 'warm_alcohol', 'good_hop': 'hoppy', 'great_hop': 'hoppy', 'hoppiness': 'hoppy',
    'hop_beer': 'hoppy', 'hop_bite': 'hoppy', 'lot_hop': 'strong_hoppy', 'hop_bomb': 'strong_hoppy',
    'hop_strong': 'strong_hoppy', 'strong_hop': 'strong_hoppy', 'big_hop': 'hoppy',
    'lot_hop': 'hoppy', 'mild_carbonation': 'light_carbonation', 'mild_fruit': 'light_fruit',
    'mild_sweet': 'semisweet', 'mild_sweetness': 'semisweet', 'mild_spice': 'light_spice',
    'mild_fruit': 'light_fruit', 'mild_bitter': 'semibitter', 'flavor_mild': 'light_flavor',
    'taste_mild': 'light_flavor', 'barrel_character': 'barrel_aged', 'barrel_note': 'barrel_aged',
    'roast_grain': 'toasted_bread', 'slightly_sticky': 'light_sticky', 'head_minimal': 'minimal_head',
    'mouthfeel_thick': 'thick_mouthfeel', 
    'mouthfeel_light': 'light_mouthfeel', 'mouthfeel_thin': 'light_mouthfeel',
    'mouthfeel_smooth': 'smooth_mouthfeel', 'mouthfeel_medium': 'medium_mouthfeel',
    'balanced_mouthfeel': 'medium_mouthfeel', 'malt_sweetness': 'sweet_malt',
    'rye_spice': 'spice_rye'
}
phrases = [
    ('light', 'vanilla'), ('light', 'tan'), ('light', 'toast'), ('light', 'coffee'),
    ('coffee', 'light'), ('light', 'beer'), ('beer', 'light'), ('light', 'toast'),
    ('smell', 'light'), ('light', 'smell'), ('slighty', 'sweet'), ('light', 'brown'),
    ('light', 'lacing'), ('light', 'nut'), ('slighty', 'bitter'), ('light', 'caramel'),
    ('light', 'aroma'), ('light', 'sweetness'), ('sweetness', 'light'), ('aroma', 'light'),
    ('head', 'light'), ('light', 'head'), ('malt', 'light'), ('light', 'malt'),
    ('light', 'hop', 'bitter'), ('flavor', 'light'), ('light', 'carbonation'),
    ('light', 'body'), ('mouthfeel', 'medium', 'light'), ('light', 'earthy'), ('medium', 'body'),
    ('light', 'khaki'), ('slightly', 'sweet'), ('slightly', 'sticky'), ('light', 'floral'),
    ('light', 'spice'), ('light', 'taste'), ('light', 'toffee'), ('slightly', 'haze'),
    ('light', 'earthy', 'hop'), ('light', 'head'), ('light', 'chocolate'), ('light', 'color'),
    ('color', 'light'), ('light', 'fruit'), ('light', 'dark', 'fruit'),
    ('strong', 'body'), ('light', 'bourbon'), ('light', 'malt'),
    ('light', 'pine'), ('light', 'alcohol'), ('light', 'tropical', 'fruit'), ('light', 'orange'),
    ('light', 'mouthfeel'), ('light', 'white', 'head'), ('light', 'haze'), ('light', 'honey'),
    ('medium', 'carbonation'), ('slightly', 'cloudy'), ('light', 'bread'), ('light', 'funk'),
    ('light', 'tart'), ('light', 'roast'), ('light', 'sour'), ('light', 'lemon'), ('light', 'pepper'),
    ('light', 'floral', 'hop'), ('light', 'amber'), ('light', 'dry'), ('light', 'sweet', 'malt'),
    ('light', 'smoke'), ('light', 'sticky'), ('light', 'toasted'), ('light', 'yellow'),
    ('light', 'bread'), ('light', 'gold'), ('light', 'banana'), ('slightly', 'fruit'),
    ('light', 'biscuit'), ('light', 'copper'), ('light', 'yeast'), ('slightly', 'hoppy'),
    ('medium', 'bread'), ('medium', 'sweet'), ('medium', 'sweetness'),
    ('strong', 'sweet'), ('strong', 'taste'), ('strong', 'malt'), ('strong', 'beer'),
    ('strong', 'alcohol'), ('strong', 'bitter'), ('strong', 'citris'), ('strong', 'aroma'),
    ('strong', 'carbonation'), ('strong', 'body'), ('strong', 'ale'),
    ('double', 'ipa'), ('english', 'ipa'), ('imperial', 'ipa'), ('belgian', 'ipa'),
    ('black', 'ipa'), ('west', 'coast', 'ipa'), ('session', 'ipa'), ('american', 'ipa'),
    ('session', 'beer'), ('dark', 'chocolate'), ('bitter', 'dark', 'chocolate'),
    ('bittersweeet', 'chocolate'), ('baker', 'chocolate'), ('milk', 'chocolate'),
    ('black', 'cherry'), ('black', 'coffee'), ('black', 'color'), ('jet', 'black'),
    ('black', 'ale'), ('opaque', 'black'), ('pitch', 'black'), ('deep', 'black'),
    ('almost', 'black'), ('nearly', 'black'), ('dark', 'brown', 'almost', 'black'),
    ('black', 'licorice'), ('near', 'black'), ('black', 'tan'), ('brown', 'ale'),
    ('nut', 'brown'), ('light', 'brown'), ('brown', 'head'), ('brown', 'sugar'),
    ('dark', 'brown', 'head'), ('dark', 'caramel'), ('dark', 'bread'), ('dark', 'malt'),
    ('dark', 'tan', 'head'), ('dark', 'tan'), ('dark', 'red'), ('dark', 'fruit'),
    ('dark', 'roast'), ('dark', 'roast', 'coffee'), ('sweet', 'dark', 'fruit'),
    ('dark', 'gold'), ('dark', 'orange'), ('dark', 'ruby'), ('dark', 'amber'),
    ('dark', 'roast', 'malt'), ('dark', 'cherry'), ('burnt', 'toast'), ('burnt', 'sugar'),
    ('burnt', 'caramel'), ('burnt', 'malt'), ('burnt', 'orange'), ('candy', 'sugar'),
    ('candied', 'sugar'), ('candi', 'sugar'), ('citrus', 'peel'), ('lemon', 'peel'),
    ('grapefruit', 'peel'), ('orange', 'peel'), ('easy', 'drinking'), ('easy', 'drink'),
    ('pale', 'ale'), ('pale', 'malt'), ('pale', 'gold'), ('pale', 'yellow'), ('pale', 'straw'),
    ('old', 'school'), ('peanut', 'butter'), ('alcohol', 'warm'), ('warm', 'alcohol'),
    ('citrus', 'hop'), ('floral', 'hop'), ('bitter', 'hop'), ('hop', 'smell'), ('hop', 'aroma'),
    ('hop', 'beer'), ('good', 'hop'), ('hop', 'bomb'), ('hop', 'bite'), ('hop', 'bitter'),
    ('pine', 'hop'), ('earthy', 'hop'), ('lot', 'hop'), ('citrus', 'hop'), ('floral', 'hop'),
    ('light', 'earthy', 'hop'), ('great', 'hop'), ('hop', 'strong'), ('sweet', 'hop'),
    ('big', 'hop'), ('mild', 'hop'), ('mosaic', 'hop'), ('dry', 'hop'), ('noble', 'hop'),
    ('mild', 'bitter'), ('mild', 'carbonation'), ('mild', 'sweet'), ('mild', 'sweetness'),
    ('mild', 'spice'), ('mild', 'fruit'), ('flavor', 'mild'), ('taste', 'mild'), ('wine', 'barrel'),
    ('bourbon', 'barrel'), ('oak', 'barrel'), ('barrel', 'aged'), ('barrel', 'character'),
    ('barrel', 'note'), ('roast', 'grain'), ('toasted', 'grain'), ('light', 'grain'),
    ('grainy', 'malt'), ('sweet', 'grain'), ('charred', 'wood'), ('sour', 'cherry'),
    ('sour', 'fruit'), ('sour', 'apple'), ('motor', 'oil'), ('fresh', 'cut'),
    ('fresh', 'cut', 'grass'), ('black', 'pepper'), ('white', 'pepper'), ('light', 'pepper'),
    ('pepper', 'spice'), ('chili', 'pepper'), ('pumpkin', 'spice'), ('herbal', 'hop'),
    ('semi', 'sweet'), ('semi', 'dry'), ('minimal', 'head'), ('head', 'minimal'),
    ('new', 'england'), ('winter', 'warmer'), ('bread', 'crust'), ('toasted', 'bread'),
    ('toasted', 'malt'), ('toasted', 'nut'), ('toasted', 'biscuit'), ('toasted', 'caramel'),
    ('light', 'toasted', 'malt'), ('pink', 'grapefruit'), ('lactic', 'acid'), ('milk', 'stout'),
    ('chocolate', 'milk'), ('frothy', 'white'), ('frothy', 'white', 'head'), ('frothy', 'head'),
    ('thick', 'mouthfeel'), ('mouthfeel', 'thick'), ('creamy', 'mouthfeel'), ('smooth', 'mouthfeel'),
    ('mouthfeel', 'light'), ('mouthfeel', 'thin'), ('light', 'mouthfeel'), ('mouthfeel', 'smooth'),
    ('medium', 'mouthfeel'), ('mouthfeel', 'medium'), ('balanced', 'mouthfeel'),
    ('east', 'coast'), ('one', 'dimensional'), ('saison', 'yeast'), ('belgian', 'yeast'),
    ('funk', 'yeast'), ('spice', 'yeast'), ('fruit', 'yeast'), ('lager', 'yeast'),
    ('graham', 'cracker'), ('white', 'grape'), ('white', 'wine'), ('bread', 'malt'),
    ('sweet', 'malt'), ('honey', 'malt'), ('malt', 'aroma'), ('roast', 'malt'),
    ('malt', 'forward'), ('hop', 'forward'), ('nut', 'malt'), ('toffee', 'malt'),
    ('malt', 'sweetness'), ('fruit', 'malt'), ('strong', 'malt'), ('chocolate', 'malt'),
    ('caramelized', 'malt'), ('toast', 'malt'), ('rich', 'malt'), ('biscuit', 'malt'),
    ('dark', 'malt'), ('wheat', 'malt'), ('cracker', 'malt'), ('crystal', 'malt'),
    ('pale', 'malt'), ('aroma', 'roast', 'malt'), ('coffee', 'roast'), ('roast', 'nut'),
    ('light', 'caramel'), ('caramelized', 'malt'),
    ('fruit', 'ester'), ('fruit', 'malt'), ('ripe', 'fruit'), ('fruit', 'hop'), ('tropical', 'fruit'),
    ('fruit', 'aroma'), ('sweet', 'fruit'), ('aroma', 'tropical', 'fruit'), ('fruit', 'forward'),
    ('dried', 'fruit'), ('sour', 'funk'), ('tart', 'fruit'), ('fruit', 'yeast'), ('bitter', 'fruit'),
    ('red', 'grapefruit'), ('sweet', 'tropical', 'fruit'), ('strong', 'fruit'), ('grass', 'hop'),
    ('tropical', 'fruit', 'hop'), ('floral', 'citrus', 'hop'), ('hop', 'oil'), ('citrus', 'pine', 'hop'),
    ('strong', 'hoppy'), ('resinous', 'hop'), ('citrus', 'hop', 'aroma'), ('hop', 'resin'), ('juicy', 'hop'),
    ('hop', 'kick'), ('citra', 'hop'), ('galaxy', 'hop'), ('grapefruit', 'hop'), ('dank', 'hop'), ('sweet', 'hop'),
    ('tropical', 'hop'), ('floral', 'spice'), ('herbal', 'spice'), ('spice', 'rye'), ('spice', 'aroma'), ('earthy', 'spice'),
    ('aroma', 'spice'), ('sweet', 'spice'), ('rye', 'spice'),('orange', 'citrus'), 
    ('orange', 'zest'), ('red', 'orange'), ('juicy', 'orange'), ('light', 'orange'),
    ('orange', 'haze'), ('orange', 'hue'), ('orange', 'yellow'), ('yellow', 'orange'), 
    ('orange', 'tangerine'), ('orange', 'marmalade'), ('orange', 'body'), 
    ('candied', 'orange'), ('blood', 'orange'), ('sweet', 'orange'),
    ('mandarin', 'orange'), ('amber', 'orange'), ('pale', 'orange'), ('clear', 'orange'), 
    ('gold', 'orange'),('citrus', 'orange'), ('orange', 'amber'), ('orange', 'white'),
    ('tropical', 'citrus'), ('sweet', 'citrus'), ('citrus', 'fruit'),
    ('juicy', 'citrus'), ('lemon', 'citrus'), ('citrus', 'zest'), ('bittersweet', 'chocolate'),
    ('oatmeal', 'stout'), ('imperial', 'stout'), ('coffee', 'stout'),
    ('barrel', 'aged', 'stout'), ('brown', 'tan'), ('black', 'tan'), ('pumpkin', 'pie'),
    ('bread', 'crust'), ('tart', 'cherry'), ('juicy', 'fruit'), ('maple', 'syrup'),
    ('chocolate', 'syrup'), ('pineapple', 'juice'), ('lemon', 'zest'), ('lemon', 'grass'), ('lemon', 'lime'),
    ('hot', 'day'), ('hot', 'summer', 'day'), ('hot', 'summer'), ('summer', 'day'), ('summer', 'beer')     
]